### PR TITLE
Make asdf loadable & fix for OSX

### PR DESCRIPTION
**Pull request by cbaggers**
- added an asd file so it can be quickloaded
- put the thread starting code in a function called gogogo
- added a package to export gogogo
- made the file you --load use asdf and call gogogo
- added bitmap-str so it uses a fallback for osx
- Also made a bunch of opinionated style fixes, sorry if that is annoying

### CODE REVIEW

**Comment by honix** [comment]
Whoa! Glad to see you there. I like, u like this. Will merge in a second!

**Comment by cbaggers** [comment]
`\o/`

**Comment by cbaggers** [comment]
oof.. I'm worried I broke something actually, I'll investigate.

Is it still working properly on your machine?

**Comment by cbaggers** [comment]
Ah I see the problem, it's todo with the current-package & eval

**Pull request merged**
